# -*- coding: utf-8 -*-
"""face_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QVBP-_w1HDoproQtpSEEPFzAZkG2wIuj
"""

!pip install dlib

!pip install face_recognition

from google.colab import drive
drive.mount('/content/drive')

!cd 'drive/My Drive/Colab Notebooks/face_recognition-master/Images' ; pwd

import os
import face_recognition

# make a list of all the available images
images = os.listdir('/content/drive/My Drive/Colab Notebooks/face_recognition-master/Images')
print(images)

# load your image
image_to_be_matched = face_recognition.load_image_file('/content/drive/My Drive/Colab Notebooks/face_recognition-master/Images/test/hylish_test.jpeg')

# encoded the loaded image into a feature vector
image_to_be_matched_encoded = face_recognition.face_encodings(
    image_to_be_matched)[0]

# iterate over each image
for image in images:
    # load the image
    try:
      current_image = face_recognition.load_image_file('/content/drive/My Drive/Colab Notebooks/face_recognition-master/Images/'+ image)
      # encode the loaded image into a feature vector
      current_image_encoded = face_recognition.face_encodings(current_image)[0]
      # match your image with the image and check if it matches
      result = face_recognition.compare_faces(
          [image_to_be_matched_encoded], current_image_encoded, tolerance = 0.5)
      # check if it was a match
      if result[0] == True:
          print ("Matched: " + image)
      else:
          print ("Not matched: " + image)
    except:
      continue